name: "Run TODO to Issue"

on: [ "push" ]
jobs:
  build:                    
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
      contents: read
    steps:
      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MSG"       >> "$GITHUB_OUTPUT"
          echo "EOF"               >> "$GITHUB_OUTPUT"

      - name: Cancel if Dependabot bump
        if: |
          startsWith(steps.get_commit.outputs.message, '⬆ bump')
        run: |
          echo "Skipping job due to commit message: ${{ steps.get_commit.outputs.message }}"
          exit 0

      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with: 
          CLOSE_ISSUES: true

        